# Generated by Django 4.2.9 on 2024-01-23 14:19

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0=default-1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default-1=trending')),
                ('m_title', models.CharField(max_length=150)),
                ('m_keyword', models.CharField(max_length=150)),
                ('m_description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.get_file_path)),
                ('s_description', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=500)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('s_price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='0=default-1=hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default-1=trending')),
                ('tag', models.CharField(max_length=150)),
                ('m_title', models.CharField(max_length=150)),
                ('m_keyword', models.CharField(max_length=150)),
                ('m_description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
